apiVersion: v1
kind: Service
metadata:
    name: djangocluster
    labels:
        app: djangocluster
spec:
    type: LoadBalancer
    ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    selector:
        app: djangocluster